local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
Normal = {fg = "#ff9000", bg = "#180c00"},
Winseparator = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#af0f00"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#7f1000"},
Comment = {fg = "#7f1000", italic = true},
["@comment"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#cc5500"},
Boolean = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
["@constant"] = {link = "Constant"},
CurSearch = {fg = "#e66f00", bg = "#7f1000"},
Cursor = {fg = "#180c00", bg = "#ff9000"},
CursorIM = {link = "Cursor"},
CursorColumn = {bg = "#2D281F"},
CursorLine = {bg = "#2D281F"},
CursorLineNr = {bg = "#2D281F"},
["@debug"] = {link = "Debug"},
["@define"] = {link = "Define"},
DiagnosticError = {fg = "#af0f00"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticUnderlineError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#cc5500"},
DiagnosticInfo = {fg = "#cc5500"},
DiagnosticFloatingHint = {link = "DiagnosticInfo"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignHint = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticUnderlineHint = {link = "DiagnosticInfo"},
DiagnosticUnderlineInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextHint = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#ff8000"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticUnderlineOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticWarn = {fg = "#BC956C"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticUnderlineWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#e66f00"},
DiffChange = {bg = "#7f1000"},
DiffDelete = {bg = "#af0f00"},
DiffText = {bg = "#433842"},
Directory = {fg = "#b34100"},
EndOfBuffer = {fg = "#524A3D"},
Error = {fg = "#af0f00"},
ErrorMsg = {fg = "#af0f00"},
Exception = {fg = "#af0f00"},
["@exception"] = {link = "Exception"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#b34100"},
FloatTitle = {fg = "#af0f00"},
FoldColumn = {fg = "#534E46"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#ff9000", bg = "#7f1000"},
Function = {fg = "#af0f00"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
Identifier = {fg = "#ff9000"},
["@field"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#534E46"},
IncSearch = {fg = "#180c00", bg = "#b34100"},
WildMenu = {link = "IncSearch"},
["@include"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#534E46"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#ff9000", bg = "#524A3D"},
ModeMsg = {fg = "#B9B4AC"},
MoreMsg = {fg = "#993800"},
MsgArea = {},
MsgSeparator = {fg = "#B9B4AC", bg = "#7f1000"},
NonText = {fg = "#534E46"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#ff9000"},
NormalNC = {fg = "#ff9000", bg = "#180c00"},
["@number"] = {link = "Number"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#B9B4AC", bg = "#7f1000"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#2D281F"},
PmenuSel = {fg = "#ff9000", bg = "#7f1000"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#524A3D"},
PreProc = {fg = "#993800"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#BC956C"},
QuickFixLine = {fg = "#cc5500"},
["@repeat"] = {link = "Repeat"},
Search = {bg = "#524A3D"},
SignColumn = {fg = "#ff9000", bg = "#180c00"},
CursorLineSign = {link = "SignColumn"},
Special = {fg = "#af0f00"},
Debug = {link = "Special"},
Delimiter = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constructor"] = {link = "Special"},
["@string.escape"] = {link = "Special"},
["@string.special"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpecialKey = {fg = "#ff8000"},
SpellBad = {sp = "#af0f00", undercurl = true},
SpellCap = {sp = "#993800", undercurl = true},
SpellLocal = {sp = "#B9B4AC", undercurl = true},
SpellRare = {sp = "#B9B4AC", undercurl = true},
Statement = {fg = "#b34100"},
Conditional = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Operator = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#B9B4AC", bg = "#7f1000"},
StatusLineNC = {fg = "#534E46", bg = "#180c00"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#F0CA93"},
["@string"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {bg = "#524A3D"},
TabLine = {fg = "#B9B4AC", bg = "#7f1000"},
TabLineFill = {bg = "#7f1000"},
TabLineSel = {fg = "#180c00", bg = "#b34100"},
["@tag"] = {link = "Tag"},
TermCursor = {reverse = true},
TermCursorNC = {reverse = true},
Title = {fg = "#ff9000"},
Todo = {fg = "#af0f00"},
Type = {fg = "#b34100"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
VertSplit = {fg = "#524A3D"},
Visual = {bg = "#524A3D"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#BC956C"},
WinBar = {fg = "#B9B4AC", bg = "#7f1000", bold = true},
WinBarNC = {fg = "#B9B4AC", bg = "#7f1000"},
lCursor = {fg = "#180c00", bg = "#ff9000"},
netrwClassify = {fg = "#993800"},
["@constant.builtin"] = {fg = "#cc5500"},
["@constant.macro"] = {fg = "#cc5500"},
["@function.builtin"] = {fg = "#993800"},
["@function.macro"] = {fg = "#993800"},
["@parameter"] = {fg = "#af0f00"},
["@punctuation"] = {fg = "#b34100"},
["@text.title"] = {fg = "#b34100"},
["@text.todo"] = {fg = "#ff8000"},
["@text.underline"] = {underline = true},
["@text.uri"] = {fg = "#cc5500", underline = true},
["@type"] = {fg = "#af0f00"},
    -- PATCH_CLOSE
    -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='witchesbrew'")

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
