local colors = {
    -- content here will not be touched
    -- PATCH_OPEN
Normal = {fg = "#FFAA33", bg = "#130C06"},
Winseparator = {link = "Normal"},
["@boolean"] = {link = "Boolean"},
Character = {fg = "#FF3300"},
["@character"] = {link = "Character"},
ColorColumn = {bg = "#613E1F"},
Comment = {fg = "#57330F", italic = true},
["@comment"] = {link = "Comment"},
["@string.documentation"] = {link = "Comment"},
["@text.literal"] = {link = "Comment"},
Conceal = {},
["@conditional"] = {link = "Conditional"},
Constant = {fg = "#CB7543"},
Boolean = {link = "Constant"},
Float = {link = "Constant"},
Number = {link = "Constant"},
["@constant"] = {link = "Constant"},
CurSearch = {fg = "#FFAA00", bg = "#3A2512"},
Cursor = {fg = "#130C06", bg = "#FFAA33"},
CursorIM = {link = "Cursor"},
CursorColumn = {bg = "#382919"},
CursorLine = {bg = "#382919"},
CursorLineNr = {bg = "#382919"},
["@debug"] = {link = "Debug"},
["@define"] = {link = "Define"},
DiagnosticError = {fg = "#FF5724"},
DiagnosticFloatingError = {link = "DiagnosticError"},
DiagnosticSignError = {link = "DiagnosticError"},
DiagnosticUnderlineError = {link = "DiagnosticError"},
DiagnosticVirtualTextError = {link = "DiagnosticError"},
DiagnosticHint = {fg = "#DC7632"},
DiagnosticInfo = {fg = "#DC7632"},
DiagnosticFloatingHint = {link = "DiagnosticInfo"},
DiagnosticFloatingInfo = {link = "DiagnosticInfo"},
DiagnosticSignHint = {link = "DiagnosticInfo"},
DiagnosticSignInfo = {link = "DiagnosticInfo"},
DiagnosticUnderlineHint = {link = "DiagnosticInfo"},
DiagnosticUnderlineInfo = {link = "DiagnosticInfo"},
DiagnosticVirtualTextHint = {link = "DiagnosticInfo"},
DiagnosticVirtualTextInfo = {link = "DiagnosticInfo"},
DiagnosticOk = {fg = "#DD8A46"},
DiagnosticFloatingOk = {link = "DiagnosticOk"},
DiagnosticSignOk = {link = "DiagnosticOk"},
DiagnosticUnderlineOk = {link = "DiagnosticOk"},
DiagnosticVirtualTextOk = {link = "DiagnosticOk"},
DiagnosticWarn = {fg = "#FFBB33"},
DiagnosticFloatingWarn = {link = "DiagnosticWarn"},
DiagnosticSignWarn = {link = "DiagnosticWarn"},
DiagnosticUnderlineWarn = {link = "DiagnosticWarn"},
DiagnosticVirtualTextWarn = {link = "DiagnosticWarn"},
DiffAdd = {bg = "#455634"},
DiffChange = {bg = "#613E1F"},
DiffDelete = {bg = "#884444"},
DiffText = {bg = "#544365"},
Directory = {fg = "#FF8833"},
EndOfBuffer = {fg = "#5A4A3A"},
Error = {fg = "#FF5724"},
ErrorMsg = {fg = "#FF5724"},
Exception = {fg = "#FF5724"},
["@exception"] = {link = "Exception"},
["@float"] = {link = "Float"},
FloatBorder = {fg = "#FF8833"},
FloatTitle = {fg = "#FF5724"},
FoldColumn = {fg = "#57330F"},
CursorLineFold = {link = "FoldColumn"},
Folded = {fg = "#FFAA33", bg = "#3A2512"},
Function = {fg = "#FFAA42"},
["@function"] = {link = "Function"},
["@method"] = {link = "Function"},
Identifier = {fg = "#FFAA33"},
["@field"] = {link = "Identifier"},
["@namespace"] = {link = "Identifier"},
["@property"] = {link = "Identifier"},
["@text.reference"] = {link = "Identifier"},
["@variable"] = {link = "Identifier"},
Ignore = {fg = "#57330F"},
IncSearch = {fg = "#130C06", bg = "#FF8833"},
WildMenu = {link = "IncSearch"},
["@include"] = {link = "Include"},
["@keyword"] = {link = "Keyword"},
["@label"] = {link = "Label"},
LineNr = {fg = "#57330F"},
LineNrAbove = {link = "LineNr"},
LineNrBelow = {link = "LineNr"},
["@macro"] = {link = "Macro"},
MatchParen = {fg = "#FFAA33", bg = "#5A4A3A"},
ModeMsg = {fg = "#FF9100"},
MoreMsg = {fg = "#CC6633"},
MsgArea = {},
MsgSeparator = {fg = "#FF9100", bg = "#3A2512"},
NonText = {fg = "#57330F"},
Whitespace = {link = "NonText"},
NormalFloat = {fg = "#FFAA33"},
NormalNC = {fg = "#FFAA33", bg = "#130C06"},
["@number"] = {link = "Number"},
["@operator"] = {link = "Operator"},
Pmenu = {fg = "#FF9100", bg = "#3A2512"},
PmenuExtra = {link = "Pmenu"},
PmenuKind = {link = "Pmenu"},
PmenuSbar = {bg = "#382919"},
PmenuSel = {fg = "#FF9742", bg = "#613E1F"},
PmenuExtraSel = {link = "PmenuSel"},
PmenuKindSel = {link = "PmenuSel"},
PmenuThumb = {bg = "#5A4A3A"},
PreProc = {fg = "#CC6633"},
Define = {link = "PreProc"},
Include = {link = "PreProc"},
Macro = {link = "PreProc"},
PreCondit = {link = "PreProc"},
["@preproc"] = {link = "PreProc"},
Question = {fg = "#FFBB33"},
QuickFixLine = {fg = "#FF8142"},
["@repeat"] = {link = "Repeat"},
Search = {bg = "#5A4A3A"},
SignColumn = {fg = "#FFAA33", bg = "#130C06"},
CursorLineSign = {link = "SignColumn"},
Special = {fg = "#FF3300"},
Debug = {link = "Special"},
Delimiter = {link = "Special"},
SpecialChar = {link = "Special"},
SpecialComment = {link = "Special"},
Tag = {link = "Special"},
["@constructor"] = {link = "Special"},
["@string.escape"] = {link = "Special"},
["@string.special"] = {link = "Special"},
["@character.special"] = {link = "SpecialChar"},
SpecialKey = {fg = "#DD8A46"},
SpellBad = {sp = "#FF3300", undercurl = true},
SpellCap = {sp = "#CC6633", undercurl = true},
SpellLocal = {sp = "#FF9100", undercurl = true},
SpellRare = {sp = "#FF9100", undercurl = true},
Statement = {fg = "#FF8833"},
Conditional = {link = "Statement"},
Keyword = {link = "Statement"},
Label = {link = "Statement"},
Operator = {link = "Statement"},
Repeat = {link = "Statement"},
StatusLine = {fg = "#FF9100", bg = "#3A2512"},
StatusLineNC = {fg = "#57330F", bg = "#130C06"},
["@storageclass"] = {link = "StorageClass"},
String = {fg = "#DD9955"},
["@string"] = {link = "String"},
["@structure"] = {link = "Structure"},
Substitute = {bg = "#5A4A3A"},
TabLine = {fg = "#FF9100", bg = "#3A2512"},
TabLineFill = {bg = "#3A2512"},
TabLineSel = {fg = "#130C06", bg = "#FF8833"},
["@tag"] = {link = "Tag"},
TermCursor = {reverse = true},
TermCursorNC = {reverse = true},
Title = {fg = "#FFAA33"},
Todo = {fg = "#FF3300"},
Type = {fg = "#FF8833"},
StorageClass = {link = "Type"},
Structure = {link = "Type"},
Typedef = {link = "Type"},
["@type.definition"] = {link = "Typedef"},
Underlined = {underline = true},
VertSplit = {fg = "#5A4A3A"},
Visual = {bg = "#5A4A3A"},
VisualNOS = {link = "Visual"},
WarningMsg = {fg = "#FFBB33"},
WinBar = {fg = "#FF9100", bg = "#3A2512", bold = true},
WinBarNC = {fg = "#FF9100", bg = "#3A2512"},
lCursor = {fg = "#130C06", bg = "#FFAA33"},
netrwClassify = {fg = "#CC6633"},
["@constant.builtin"] = {fg = "#DC7632"},
["@constant.macro"] = {fg = "#DC7632"},
["@function.builtin"] = {fg = "#CC5500"},
["@function.macro"] = {fg = "#CC5500"},
["@parameter"] = {fg = "#FF3300"},
["@punctuation"] = {fg = "#FF8833"},
["@text.title"] = {fg = "#FF8833"},
["@text.todo"] = {fg = "#FF9457"},
["@text.underline"] = {underline = true},
["@text.uri"] = {fg = "#CB7543", underline = true},
["@type"] = {fg = "#FF3300"},
    -- PATCH_CLOSE
    -- content here will not be touched
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='witchesbrew'")

-- apply highlight groups
for group, attrs in pairs(colors) do
    vim.api.nvim_set_hl(0, group, attrs)
end
